version: '2'
services:
    backend_todolist-app:
        image: backend_todolist
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://backend_todolist-mysql:3306/backend_todolist?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    backend_todolist-mysql:
        extends:
            file: mysql.yml
            service: backend_todolist-mysql
